# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4272b79889fb38edde3118204c6af3d0b04ce2d6a5b2f449c5fc1ffe2bd5c118f038d5008e5d5d4139b38d3b8cbbfe0ef6198f10dc60533690c78e0284d5a7c5

test:
  secret_key_base: ea856cee8a61a60d5d14c61c443f16f3416a14286e61ea05c230c2e0e8c30f06cdc86b70234a2b252cc4eb515e4262e318ce557b4d108d5e0401191ec130ed64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 4b54c843690b09679e4a3d8301cee4678f94e88128cc21c5acd711a2a3c1b6bdcf5057d89010f7352a95edaf72e18abfacf95c0d283679bacdf839219baaace8
