# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Sentence.create(sentence: "こんにちは", source_flag: "3")
Sentence.create(sentence: "元気ですか？", source_flag: "3")
Sentence.create(sentence: "お話しませんか", source_flag: "3")
Sentence.create(sentence: "お疲れ様です", source_flag: "3")
Sentence.create(sentence: "どうかしました？", source_flag: "3")
Sentence.create(sentence: "調子はどうですか？", source_flag: "3")
Sentence.create(sentence: "趣味はなんですか？", source_flag: "3")
Sentence.create(sentence: "何をしていますか？", source_flag: "3")
Sentence.create(sentence: "仕事はどうですか？", source_flag: "3")
Sentence.create(sentence: "好きなスポーツは？", source_flag: "3")
Sentence.create(sentence: "休日はは何をしていますか？", source_flag: "3")
Sentence.create(sentence: "好きな料理は何ですか？", source_flag: "3")
Sentence.create(sentence: "得意な料理は何ですか？", source_flag: "3")
Sentence.create(sentence: "旅行は好きですか？", source_flag: "3")
Sentence.create(sentence: "サッカーは好きですか？", source_flag: "3")
Sentence.create(sentence: "野球は好きですか？", source_flag: "3")
Sentence.create(sentence: "バスケは好きですか？", source_flag: "3")
Sentence.create(sentence: "お腹がすきました", source_flag: "3")
Sentence.create(sentence: "お寿司が食べたいです", source_flag: "3")
Sentence.create(sentence: "お肉が食べたいです", source_flag: "3")
Sentence.create(sentence: "おやつが食べたいです", source_flag: "3")
Sentence.create(sentence: "眠いです", source_flag: "3")
Sentence.create(sentence: "今日は眠たいですね", source_flag: "3")
Sentence.create(sentence: "休憩ですか？", source_flag: "3")
Sentence.create(sentence: "今日も疲れましたね", source_flag: "3")
Sentence.create(sentence: "進捗どうですか", source_flag: "3")
Sentence.create(sentence: "進捗ありません", source_flag: "3")
Sentence.create(sentence: "仕事はもういいんですか？", source_flag: "3")
Sentence.create(sentence: "息してますか？", source_flag: "3")
